### ISSUE TITLE
Folders and files name are broken

### ISSUE THREAD

**Issue by MartyVador** [Kanjirito/simple-manga-downloader#20]
Folders and files name are broken if there is a special character in the name of the downloaded manga. 
Example : https://manganelo.com/manga/cr918121

Keep up the great work !

**Comment by Kanjirito** [comment]
That's a Windows issue, I never really thought about Windows support (had no idea it even worked, probably should have mentioned it somewhere in the README) and since nobody complained I never looked into it. A way around it for now is to use the `-n / --name` argument to give it a different name.

**Comment by MartyVador** [comment]
I'm running it on a debian server from console. I'm using the tracked list, is there a way to manually set a name in the tracked list ?

**Comment by Kanjirito** [comment]
> I'm running it on a debian server from console.

Well that's unexpected, what happens to the filename?
> is there a way to manually set a name in the tracked list ?

No, though I probably should make the downloader not check names for the tracked manga and just use the saved name (which would also another issue).

**Comment by MartyVador** [comment]
> Well that's unexpected, what happens to the filename?

For example, the manga _An Oldman In Counterworld._ (https://manganelo.com/manga/di918304) the directory name is set as _ADNNMD~W_
The period in the name only breaks the directory name but if there's a colon in the name like this manga _Isekai Yururi Kikou: Raising Children While Being An Adventurer_ (https://manganelo.com/manga/cr918121), the directory name is set as _IEY1ZI~B_ and the file name are broken (ex : _I1GNWN~Y_).

**Comment by Kanjirito** [comment]
That is very confusing, I have no idea why the filenames end up *that* messed up. Are you using the downloader in some script or something or are you doing it directly? Can you create a file with one of those characters in any other way (for example does `touch test:test.txt` work normally)? Can your create a file with those characters through python like this:
```python
with open("test:test.txt", "w") as f:
     f.write("something")
```

**Comment by MartyVador** [comment]
> Are you using the downloader in some script or something or are you doing it directly?

I'm using it directly

> Can you create a file with one of those characters in any other way (for example does touch test:test.txt work normally)

It works

> Can your create a file with those characters through python like this

It works too

Though I needed to escape the colon each time in order to remove the file. `rm test\:test.txt`

**Comment by Kanjirito** [comment]
Interesting. Is the name of the manga correct in the printed output (when you dowload or list the tracked titles)?

**Comment by MartyVador** [comment]
Yes it is displayed correctly on the output

**Comment by Kanjirito** [comment]
Commit 754476d adds the tracked title overwrite support, I want to add more stuff before I make a new release so if you don't want to wait for that you can install from the git repo for now (`pip install --force-reinstall git+https://github.com/Kanjirito/simple-manga-downloader` will do it if you are only using pip). There isn't a way to change the title through the downloader for now so you will have to manually edit the title in the config.

**Comment by MartyVador** [comment]
Sorry for the delay ! 

> your Debian version

`Operating System: Debian GNU/Linux 10 (buster) | Kernel: Linux 4.19.0-11-amd64`

> which image was installed

`debian-10.6.0-amd64-netinst.iso`

> you can create a file

Works without any problem on python 3.7.3 and python 2.7.16
The workaround works great, I edited the tracked title and it works without a itch. 

Maybe it is a problem with locale ? I'll try later with a fresh default install of debian.

Thank you !

**Comment by Kanjirito** [comment]
I have no idea how it happens that you can do it normally but in the downloader it screws up. My last idea is that maybe pathlib for some reason screws something up but I really doubt that. If you want to test that:
```python
from pathlib import Path

path = Path("Test") / "Manga" / "Isekai Yururi Kikou: Raising Children While Being An Adventurer"
path.mkdir(parents=True, exist_ok=True)
```

The commit 5b80adc adds a character replacement list so you can set custom rules for stuff that breaks without having to manually change the name every time. If you find anything out let me know, I'm curious what is causing this strange behavior.

**Comment by Kanjirito** [comment]
Since there are now ways to avoid this problem and I can't recreate this bug I'm gonna close this for now.
