### ISSUE TITLE
Won't Recognize Chapters When Volumes Restart Numbering

### ISSUE THREAD

**Issue by danieljwhitten** [Kanjirito/simple-manga-downloader#21]
Hey,

Just noticed that when one manga entry has multiple volumes, but the chapter numbers restart in each one (common in anthologies), it only grabs the first volume.

Eg. https://mangakakalot.com/read-na9ou158524497114 has 25 chapters over 4 volumes, but the script only grabs the 16 from volume one, and won't recognize Vol 2 - Chapter 1 as the next chapter. The issue is the same for any of the supported sites, as long as the chapter numbering starts again each volume.

Thanks for all your hard work, by the way!

**Comment by Kanjirito** [comment]
I know that this is an issue but I thought only mangasee had this way of numbering so after I dropped support for that site I never bothered trying to fix it. It's doable but I'd have to decide how to do it the most sane way. I'll mention this in the known issues.

This creates different problems though. How should the downloader work if you select a chapter but there are 2 chapters with that number? I could make the chapter numbers continue normally (so in your case the first chapter from season 2 would be chapter 17) but that would make it confusing when comparing the chapter numbers from the downloader and the ones on the site. It would also need to deal with missing chapters in those cases. Or I could include the volume somewhere in the directory name but that would force me to change it for every manga and a lot of manga doesn't have seasons/volumes so it would be pretty useless.

**Comment by Kanjirito** [comment]
I've been trying to figure out a solution to this and I cannot come up with a way to fix this that won't break something else. Unless I find a way to have volume/season in directory names for chapters without breaking sorting I can't do anything and it will just have to stay like this.

**Comment by Kanjirito** [comment]
There's a workaround added in 6f7fbb3. The downloader will now ask for a new number if it's already taken so the user now has to decide how they want to deal with the problem. This might change if I come up with a better solution.
