### ISSUE TITLE
example links or something of the sort

### ISSUE THREAD

**Issue by Blackbeard25** [Kanjirito/simple-manga-downloader#22]
I am trying to get this working, however i am having an issue getting it to download from mangadex just reporting that its a wrong link. I think it would help to have an example link for each of the supported sources in the USAGE.md file to help clarify formatting for the new user like myself

**Comment by Blackbeard25** [comment]
I have found my issue and i will leave the solution here, when downloading from mangadex, the url needs to look like [https://mangadex.org/title/32775/fechippuru-our-innocent-love](https://mangadex.org/title/32775/fechippuru-our-innocent-love), not like [https://mangadex.org/title/32775/](https://mangadex.org/title/32775/).  Both will take you to the same place in your web browser, however SMD appears to only work with the latter url

Hope this helps

**Comment by Kanjirito** [comment]
I could add example URLs but I'd have to check from time to time if they still work so I'm probably not gonna do it. I don't believe this to be a real issue. You are right that the /manga/ID type links should work and I'll add support for them but I'm curious where do you even get a link like that? The site seems to always link to /title/ID

**Comment by Blackbeard25** [comment]
Getting the /manga/id is from tachyomi, as that is my reader on my phone so it was easier to just send the link from my phone then searching for each one

**Comment by Kanjirito** [comment]
Expected it to be something like that. Don't know where they get that link from but it's a valid one so it should be working with the downloader.
Don't know when I'll make a new release with the fix so if you want it now you can get it by installing from the git repo. Thanks for letting me know about this.

**Comment by Blackbeard25** [comment]
It's not a huge deal for me as I will be using the tracker for the most part to prevent me from having to input the URLs everytime there is an update
