### ISSUE TITLE
Can't Download Chapters With Quotation Marks

### ISSUE THREAD

**Issue by 98263549836745-3904568** [Kanjirito/simple-manga-downloader#27]
When downloading entire series from either mangadex or manganato, the program crashes on certain chapters. I've noticed that this only seems to happen when the chapter has quotation marks in the title.

As an example, chapter 31 of this manga can't be downloaded:
https://mangadex.org/title/7a9d76c3-42b9-4bcf-81d7-ad307d2ea971/jojo-s-bizarre-adventure-part-8-jojolion-official-colored?page=1

**Comment by Kanjirito** [comment]
I'm guessing that you are using Windows and `"` is not allowed in filenames. I somehow missed that one when doing the character replacement rules. I'm gonna add it to the defaults in the next release. You can also just add the rule yourself with:
```
smd conf --rule-add "\"" ""
```
That will remove all `"` from file names.
